export const DUMMY_EVENTS = [
  {
    id: 'evt-1',
    title: 'Paws & Solace: Weekend Stray Adoption & Shelter Support',
    description: 'Join us for our monthly flagship Rescue Rituals adoption day! Meet over 25 vaccinated, vetted stray dogs and cats looking for loving foster or permanent homes.',
    date: '2026-10-03',
    time: '10:00 AM - 04:30 PM',
    location: 'Cubbon Park Pavilion Gardens, Bengaluru',
    category: 'Animal Rescue',
    image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=1200&q=80',
    capacity: 150,
    attendeesCount: 94,
    price: 'Free',
    organizer: 'Rescue Rituals Foundation',
    isGoing: false,
  },
  {
    id: 'evt-2',
    title: 'Sunset Sound Bath & Breathwork Meditation',
    description: 'Reset your nervous system with Tibetan singing bowls, conscious pranayama breathwork, and guided somatic relaxation at dusk.',
    date: '2026-10-06',
    time: '05:30 PM - 07:30 PM',
    location: 'The Sanctuary Rooftop Studio, Indiranagar',
    category: 'Wellness',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80',
    capacity: 40,
    attendeesCount: 38,
    price: '₹499',
    organizer: 'Prana Resonance Collective',
    isGoing: false,
  },
  {
    id: 'evt-3',
    title: 'Frontend Micro-Interactions & React Workshop',
    description: 'A deep-dive hands-on workshop covering smooth UI animations, state handling, and performant design patterns.',
    date: '2026-10-10',
    time: '07:00 PM - 09:00 PM',
    location: 'Virtual (Zoom / Discord Stage)',
    category: 'Workshops',
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
    capacity: 250,
    attendeesCount: 180,
    price: 'Free',
    organizer: 'DevCraft Guild',
    isGoing: false,
  },
  {
    id: 'evt-4',
    title: 'Native Seed Bombing & Urban Rewilding Drive',
    description: 'Help restore city green cover by preparing and dispersing native seed balls packed with indigenous tree seeds.',
    date: '2026-10-12',
    time: '07:30 AM - 11:00 AM',
    location: 'Agara Lake Wetland Periphery, HSR Layout',
    category: 'Eco & Nature',
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80',
    capacity: 80,
    attendeesCount: 65,
    price: 'Free',
    organizer: 'Green Bengaluru Action',
    isGoing: false,
  },
  {
    id: 'evt-5',
    title: 'Acoustic Candlelight Jam & Poetry Circle',
    description: 'An intimate evening of original indie songs, spoken word poetry, and acoustic warmth with hot cocoa.',
    date: '2026-10-15',
    time: '06:30 PM - 09:30 PM',
    location: 'Artisan Haven Attic Cafe, Indiranagar',
    category: 'Music & Arts',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
    capacity: 50,
    attendeesCount: 47,
    price: '₹250',
    organizer: 'Living Room Sessions',
    isGoing: false,
  },
  {
    id: 'evt-6',
    title: 'Mindful Pottery & Clay Sculpting Session',
    description: 'Discover tactile mindfulness through hand-pinched terracotta clay sculpting and pottery wheel techniques.',
    date: '2026-10-18',
    time: '11:00 AM - 02:00 PM',
    location: 'Terra Earthworks Studio, Koramangala',
    category: 'Wellness',
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80',
    capacity: 30,
    attendeesCount: 22,
    price: '₹850',
    organizer: 'Clay & Soul Guild',
    isGoing: false,
  }
];
