export const CATEGORY_OPTIONS = [
  'Animal Rescue',
  'Wellness',
  'Workshops',
  'Eco & Nature',
  'Music & Arts',
  'Community',
  'Sound Healing',
  'Yoga & Mindfulness',
  'Shelter Volunteering',
  'Food Drives & Nourishment',
  'Art & Creative Therapy',
  'Tree Planting & Rewilding',
  'Fitness & Outdoor Trek',
  'Youth & Education',
];
